/*

 * To change this license header, choose License Headers in Project Properties.

 * To change this template file, choose Tools | Templates

 * and open the template in the editor.

 */

package studentverdict;



import java.awt.Dimension;

import java.awt.GridBagLayout;

import java.awt.HeadlessException;

import java.awt.Image;

import java.awt.Toolkit;

import java.awt.image.BufferedImage;

import java.io.File;

import java.io.IOException;

import java.sql.Connection;

import java.sql.DriverManager;

import java.sql.PreparedStatement;

import java.sql.ResultSet;

import java.sql.SQLException;

import java.sql.SQLIntegrityConstraintViolationException;

import java.sql.Statement;

import javax.imageio.ImageIO;

import javax.swing.ButtonGroup;

import javax.swing.ImageIcon;

import javax.swing.JFileChooser;

import javax.swing.JFrame;

import javax.swing.JOptionPane;



/**

 *

 * @author owner

 */

public class Dashboard extends javax.swing.JFrame {



    /**

     * Creates new form Dashboard

     */

    

        Statement st;

    Connection con;

    PreparedStatement pst;

    ResultSet rs;

    

    String username = "root";

    String password = "";

    String url = "jdbc:mysql://localhost:3306/student_verdict";

    public  int autostudentid;

    

    

    // panel 

     AddStaff addstaff = new AddStaff();

      AddJudgement addjudgement= new AddJudgement();

      Violation addviolation = new Violation();

      PassEvidence addevidence = new PassEvidence();

     public PassVerdict addpassverdict = new PassVerdict();

     GoodConduct goodconduct = new GoodConduct();

     SystemViews systemviews = new SystemViews();


     

       

    

    

    public Dashboard() {

        initComponents();

        groupgender();

        loadavater();

        disposeall();
           loadnextid ();
     

    }
    
    public void  loadnextid (){
         try{
             con = DriverManager.getConnection(url,username,password);
             st = con.createStatement();
             String selectstudentid = "SELECT studentREG FROM student  ";
            pst = con.prepareStatement(selectstudentid);
            rs = pst.executeQuery();
                  
            while(rs.next()){
               
              //autostudentid ++; 
             //txtregnumber.setText(autostudentid+"");
            
            }
            
           
         }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "error"+ ex,"Student verdict",JOptionPane.INFORMATION_MESSAGE);  
         }
    }
    
    
    

    public void groupgender(){

        ButtonGroup Groupgender = new ButtonGroup();

        Groupgender.add(rbmale);

        Groupgender.add(rbfemale);

        Groupgender.clearSelection();

    }

    public void loadavater(){

        ImageIcon img1;

         img1 = new ImageIcon("images/studentavatar.png");

         lbstudentavatarlink.setText("images/studentavatar.png");

        lbstudentimage.setIcon(img1);

    }

    public void resizedimage(String resizedavatar) throws IOException{

        BufferedImage img = ImageIO.read(new File(resizedavatar));

Image scaled = img.getScaledInstance(200, 200, Image.SCALE_SMOOTH);

ImageIcon icon = new ImageIcon(scaled);

lbstudentimage.setIcon(icon);

    }

    

    public void disposeall(){

        jpaddstudent.setVisible(false);

             addstaff.setVisible(false);

             this.add(addstaff);

             addjudgement.setVisible(false);

             this.add(addjudgement);

             addviolation.setVisible(false);

             this.add(addviolation);

             addevidence.setVisible(false);

             this.add(addevidence);

             addpassverdict.setVisible(false);

             this.add(addpassverdict);

             systemviews.setVisible(false);

             this.add(systemviews);
             goodconduct.setVisible(false);
             this.add(goodconduct);
             
          

             



    }

       



    /**

     * This method is called from within the constructor to initialize the form.

     * WARNING: Do NOT modify this code. The content of this method is always

     * regenerated by the Form Editor.

     */

    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpaddstudent = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtregnumber = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtstudentsurname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtstudentothername = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtstudentid = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtstudentphone = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtstudentemail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbstudentavatarlink = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        rbmale = new javax.swing.JRadioButton();
        rbfemale = new javax.swing.JRadioButton();
        jdcstudentdob = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        btnsavestudent = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        lbstudentimage = new javax.swing.JLabel();
        btnfilechooser = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmpassverdict = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        menjudgement = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        menaddstudent = new javax.swing.JMenuItem();
        menaddstaff = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("STUDENT VERDICT");
        setMinimumSize(new java.awt.Dimension(1100, 600));
        setPreferredSize(new java.awt.Dimension(1100, 600));
        getContentPane().setLayout(null);

        jpaddstudent.setBackground(new java.awt.Color(255, 255, 255));
        jpaddstudent.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Registration Number :");

        txtregnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtregnumberActionPerformed(evt);
            }
        });
        txtregnumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtregnumberKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtregnumberKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Surname :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Other Name :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("ID Number :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Phone Number :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Email Adress :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Gender :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Date Of Birth :");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Image Link :");

        rbmale.setText("MALE");
        rbmale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbmaleActionPerformed(evt);
            }
        });

        rbfemale.setText("FEMALE");

        btnsavestudent.setText("SAVE STUDENT");
        btnsavestudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsavestudentActionPerformed(evt);
            }
        });

        jButton4.setText("RESET FORM");

        jButton5.setText("UPDATE STUDENT");

        jButton6.setText("SEARCH");

        jButton7.setText("DELETE STUDENT ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(btnsavestudent, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jButton6)
                .addGap(26, 26, 26)
                .addComponent(jButton7)
                .addContainerGap(110, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsavestudent, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        lbstudentimage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnfilechooser.setText("Choose file");
        btnfilechooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfilechooserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpaddstudentLayout = new javax.swing.GroupLayout(jpaddstudent);
        jpaddstudent.setLayout(jpaddstudentLayout);
        jpaddstudentLayout.setHorizontalGroup(
            jpaddstudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpaddstudentLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jpaddstudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpaddstudentLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txtregnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jdcstudentdob, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpaddstudentLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(txtstudentsurname, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(rbmale)
                        .addGap(49, 49, 49)
                        .addComponent(rbfemale))
                    .addGroup(jpaddstudentLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(txtstudentothername, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(lbstudentavatarlink, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpaddstudentLayout.createSequentialGroup()
                        .addGroup(jpaddstudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpaddstudentLayout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(txtstudentid, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpaddstudentLayout.createSequentialGroup()
                                .addGroup(jpaddstudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40)
                                .addGroup(jpaddstudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtstudentphone, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtstudentemail, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbstudentimage, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(152, 152, 152))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpaddstudentLayout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addGroup(jpaddstudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpaddstudentLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpaddstudentLayout.createSequentialGroup()
                        .addComponent(btnfilechooser, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(179, 179, 179))))
        );
        jpaddstudentLayout.setVerticalGroup(
            jpaddstudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpaddstudentLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jpaddstudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtregnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpaddstudentLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jpaddstudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel8)
                            .addComponent(jdcstudentdob, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(10, 10, 10)
                .addGroup(jpaddstudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtstudentsurname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpaddstudentLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jpaddstudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7)
                            .addComponent(rbmale)
                            .addComponent(rbfemale))))
                .addGap(17, 17, 17)
                .addGroup(jpaddstudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpaddstudentLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3))
                    .addComponent(txtstudentothername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(lbstudentavatarlink, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jpaddstudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpaddstudentLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jpaddstudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpaddstudentLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel4))
                            .addComponent(txtstudentid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jpaddstudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtstudentphone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jpaddstudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpaddstudentLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel6))
                            .addComponent(txtstudentemail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpaddstudentLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lbstudentimage, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnfilechooser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        getContentPane().add(jpaddstudent);
        jpaddstudent.setBounds(40, 20, 1100, 580);

        jMenu1.setText("VERDICT");

        jmpassverdict.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jmpassverdict.setText("ADD EVIDENCE");
        jmpassverdict.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmpassverdictActionPerformed(evt);
            }
        });
        jMenu1.add(jmpassverdict);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("PASS VERDICT");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem7.setText("VIEW VERDICT");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("VIEW");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu3.setText("REPORT");

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        jMenuItem3.setText("VIEW CERTIFICATE");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        jMenuItem6.setText("GOOD CONDUCT");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("CRIME");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("ADD CRIME");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        menjudgement.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        menjudgement.setText("JUDGDEMENT");
        menjudgement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menjudgementActionPerformed(evt);
            }
        });
        jMenu4.add(menjudgement);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("ACCOUNT");

        menaddstudent.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        menaddstudent.setText("ADD STUDENT");
        menaddstudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menaddstudentActionPerformed(evt);
            }
        });
        jMenu5.add(menaddstudent);

        menaddstaff.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        menaddstaff.setText("ADD STAFF");
        menaddstaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menaddstaffActionPerformed(evt);
            }
        });
        jMenu5.add(menaddstaff);

        jMenuItem8.setText("LOGOUT");
        jMenu5.add(jMenuItem8);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents



    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed

        // TODO add your handling code here:
        
        
 disposeall();
        goodconduct.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed



    private void rbmaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbmaleActionPerformed

        // TODO add your handling code here:

       

        if(rbfemale.isSelected()){

       groupgender();

       rbmale.isSelected();

    }else{

            rbmale.isSelected();

        }

        

    }//GEN-LAST:event_rbmaleActionPerformed



    private void btnfilechooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfilechooserActionPerformed

         JFrame frame = new JFrame("Swing Tester");

      frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

      

      frame.setSize(560, 200);      

      frame.setLocationRelativeTo(null);  

      frame.setVisible(false);

        

         JFileChooser fileChooser = new JFileChooser("C:\\Projects\\StudentVerdict\\images");

            int option = fileChooser.showOpenDialog(frame);

            if(option == JFileChooser.APPROVE_OPTION){

               File file = fileChooser.getSelectedFile();

               File folder = fileChooser.getCurrentDirectory();

               lbstudentavatarlink.setText(folder.getAbsolutePath() + "/" + file.getName());

               String resizedavatar = folder.getAbsolutePath() + "/" + file.getName();

              

               // try load resized image

               

               try {

            // TODO add your handling code here:

            resizedimage(resizedavatar);

        } catch (IOException ex) {

            JOptionPane.showConfirmDialog(null, ex );

        }

            }else{

               lbstudentavatarlink.setText("Open command canceled");

               loadavater();

            }

   

    }//GEN-LAST:event_btnfilechooserActionPerformed



    private void btnsavestudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsavestudentActionPerformed

        try {

            

            // get gender 

           String studentgender = "";

           if(rbmale.isSelected()){

               studentgender = "MALE";

           }

           if(rbfemale.isSelected()){

               studentgender = "FEMALE";

           }

           System.out.print(studentgender);

           // GET Date 

           

            java.util.Date dob;

            java.sql.Date studentdob;

            dob =  jdcstudentdob.getDate();

            studentdob = new java.sql.Date(dob.getTime());

            // TODO add your handling code here:

            con = DriverManager.getConnection(url,username,password);

             st = con.createStatement();

            // inserting student personal details

            String sqlstudentdetails = "INSERT INTO student (studentREG,studentsurname,studentothername,studentIDnumber,studentphone,"

                    + "studentemail,studentgender,studentDOB,studentimage) VALUES"

                    + " ('"+txtregnumber.getText()+"','"+txtstudentsurname.getText()+"','"+txtstudentothername.getText()+"','"+txtstudentid.getText()+"',"

                    + "'"+txtstudentphone.getText()+"','"+txtstudentemail.getText()+"','"+studentgender+"','"+studentdob+"',"

                    + "'"+lbstudentavatarlink.getText()+"')";

           st.execute(sqlstudentdetails);

            JOptionPane.showMessageDialog(null, "<HTML><i style=\"color: green; font-size: 12px;\">New Student Registered</i></HTML>","School",JOptionPane.INFORMATION_MESSAGE);

        }catch(SQLIntegrityConstraintViolationException e){

        JOptionPane.showMessageDialog(null, "<HTML><i style=\"color: red; font-size: 12px;\">Student Already Exists</i></HTML>","School",JOptionPane.WARNING_MESSAGE);  

      }

      catch(HeadlessException | SQLException ex){

   JOptionPane.showMessageDialog(null, "error"+ ex,"School",JOptionPane.INFORMATION_MESSAGE);



       }

      catch(NullPointerException npx){

        JOptionPane.showMessageDialog(null,"Please select Date !","School",JOptionPane.INFORMATION_MESSAGE);

        } 

    }//GEN-LAST:event_btnsavestudentActionPerformed



    private void menaddstaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menaddstaffActionPerformed

        // TODO add your handling code here:

        /*jpaddstudent.setVisible(false);

        AddStaff addstaff = new AddStaff();

        addstaff.setVisible(true);

        this.add(addstaff);*/

        disposeall();

        addstaff.setVisible(true);

        

    }//GEN-LAST:event_menaddstaffActionPerformed



    private void menaddstudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menaddstudentActionPerformed

        // TODO add your handling code here:
         disposeall();
        jpaddstudent.setVisible(true);

    }//GEN-LAST:event_menaddstudentActionPerformed



    private void menjudgementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menjudgementActionPerformed

        // TODO add your handling code here:
        disposeall();
        addjudgement.setVisible(true);

    }//GEN-LAST:event_menjudgementActionPerformed



    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        // TODO add your handling code here:
        disposeall();
        addviolation.setVisible(true);

    }//GEN-LAST:event_jMenuItem1ActionPerformed



    private void jmpassverdictActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmpassverdictActionPerformed

        // TODO add your handling code here:
        disposeall();
        addevidence.setVisible(true);

    }//GEN-LAST:event_jmpassverdictActionPerformed



    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed

        // TODO add your handling code here:
         disposeall();
        addpassverdict.setVisible(true);

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
          disposeall();
        systemviews.setVisible(true);
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        this.dispose();
       JFrame printer = new PrinGoodConduct();
                printer.setVisible(true);
                Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
                int w = dim.width;
                int h = dim.height;
                printer.setSize(w, h);
                printer.setLocation(0,0);
                 printer.setExtendedState(JFrame.MAXIMIZED_BOTH);
                printer.setLayout(new GridBagLayout());
               // this.dispose();
        
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
          this.dispose();
       JFrame verdictprinter = new PrinVerdictCertificate();
                verdictprinter.setVisible(true);
                Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
                int w = dim.width;
                int h = dim.height;
                verdictprinter.setSize(w, h);
                verdictprinter.setLocation(0,0);
                 verdictprinter.setExtendedState(JFrame.MAXIMIZED_BOTH);
                verdictprinter.setLayout(new GridBagLayout());
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void txtregnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtregnumberActionPerformed
        // TODO add your handling code here:
        
   
    }//GEN-LAST:event_txtregnumberActionPerformed

    private void txtregnumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtregnumberKeyPressed
        // TODO add your handling code here:
        
       
    }//GEN-LAST:event_txtregnumberKeyPressed

    private void txtregnumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtregnumberKeyReleased
        // TODO add your handling code here:
          int pos = txtregnumber.getCaretPosition();
        txtregnumber.setText(txtregnumber.getText().toUpperCase());
        txtregnumber.setCaretPosition(pos);
    }//GEN-LAST:event_txtregnumberKeyReleased



    /**

     * @param args the command line arguments

     */

    public static void main(String args[]) {

        /* Set the Nimbus look and feel */

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">

        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.

         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 

         */

        try {

            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {

                if ("Nimbus".equals(info.getName())) {

                    javax.swing.UIManager.setLookAndFeel(info.getClassName());

                    break;

                }

            }

        } catch (ClassNotFoundException ex) {

            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {

            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {

            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {

            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        }

        //</editor-fold>



        /* Create and display the form */

        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {

                JFrame dash = new Dashboard();

                dash.setVisible(true);

                Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();

                int w = dim.width;

                int h = dim.height;

                dash.setSize(w, h);

                dash.setLayout(new GridBagLayout());

            }

        });

    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnfilechooser;
    private javax.swing.JButton btnsavestudent;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel1;
    private com.toedter.calendar.JDateChooser jdcstudentdob;
    private javax.swing.JMenuItem jmpassverdict;
    private javax.swing.JPanel jpaddstudent;
    private javax.swing.JTextField lbstudentavatarlink;
    private javax.swing.JLabel lbstudentimage;
    private javax.swing.JMenuItem menaddstaff;
    private javax.swing.JMenuItem menaddstudent;
    private javax.swing.JMenuItem menjudgement;
    private javax.swing.JRadioButton rbfemale;
    private javax.swing.JRadioButton rbmale;
    private javax.swing.JTextField txtregnumber;
    private javax.swing.JTextField txtstudentemail;
    private javax.swing.JTextField txtstudentid;
    private javax.swing.JTextField txtstudentothername;
    private javax.swing.JTextField txtstudentphone;
    private javax.swing.JTextField txtstudentsurname;
    // End of variables declaration//GEN-END:variables

}

