/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentverdict;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author owner
 */
public class GoodConduct extends javax.swing.JPanel {

    /**
     * Creates new form GoodConduct
     */
    
    Statement st;
    Connection con;
    PreparedStatement pst;
    ResultSet rs,rsverdict;
    
    String username = "root";
    String password = "";
    String url = "jdbc:mysql://localhost:3306/student_verdict";
    
    public GoodConduct() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtstudentregforgoodconduct = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Student  ID :");

        jButton1.setText("Generate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(253, 253, 253)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(txtstudentregforgoodconduct, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118)
                .addComponent(jButton1)
                .addContainerGap(168, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtstudentregforgoodconduct, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1))
                    .addComponent(jLabel1))
                .addContainerGap(485, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       String reg = null;
        try{
            con = DriverManager.getConnection(url,username,password);
            st = con.createStatement();
            
            
         String selectstudent = "SELECT * FROM student WHERE studentREG = ?  ";
            pst = con.prepareStatement(selectstudent);
            pst.setString(1, (String) txtstudentregforgoodconduct.getText());
            rs = pst.executeQuery();
                  
            if(rs.next()){
               
               reg = rs.getString("studentREG");
               String surname = rs.getString("studentsurname");
               String othername = rs.getString("studentothername");
               String idnumber = rs.getString("studentIDnumber");
               String phone = rs.getString("studentphone");
               String email = rs.getString("studentemail");
               String gender = rs.getString("studentgender");
               String dob = rs.getString("studentDOB");
               String link = rs.getString("studentimage");
               
                  String selectstudentverdict = "SELECT * FROM verdict WHERE studentREG = '"+reg+"'  ";
            pst = con.prepareStatement(selectstudentverdict);
            rsverdict = pst.executeQuery();
            if(rsverdict.next()){
                JOptionPane.showMessageDialog(null, "Student : " + txtstudentregforgoodconduct.getText() + surname + "criminal");
                
            }else{
               JOptionPane.showMessageDialog(null, "Student : " + txtstudentregforgoodconduct.getText() + "clean"); 
            }
               
            }else{
                JOptionPane.showMessageDialog(null, "Student : " + txtstudentregforgoodconduct.getText() + "Not found");
            }
        
            
                         }
    catch(SQLException ex){
    JOptionPane.showMessageDialog(null, ex);
}
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtstudentregforgoodconduct;
    // End of variables declaration//GEN-END:variables
}
