/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentverdict;

import java.awt.Dimension;
import java.awt.GridBagLayout;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static studentverdict.AddAccount.hashpassword;

/**
 *
 * @author owner
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
         Statement st;
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    
    String username = "root";
    String password = "";
    String url = "jdbc:mysql://localhost:3306/student_verdict";
    
    
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtusernamelogin = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jploginpassword = new javax.swing.JPasswordField();
        bntlogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1100, 600));
        setPreferredSize(new java.awt.Dimension(1100, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("USERNAME :");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(280, 60, 89, 17);

        txtusernamelogin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(txtusernamelogin);
        txtusernamelogin.setBounds(200, 100, 240, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("PASSWORD :");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(280, 170, 91, 17);

        jploginpassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(jploginpassword);
        jploginpassword.setBounds(200, 220, 250, 40);

        bntlogin.setBackground(new java.awt.Color(153, 255, 153));
        bntlogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bntlogin.setText("LOGIN NOW");
        bntlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntloginActionPerformed(evt);
            }
        });
        jPanel2.add(bntlogin);
        bntlogin.setBounds(180, 310, 310, 50);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(230, 70, 660, 450);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1100, 570);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bntloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntloginActionPerformed
        // TODO add your handling code here:
        
        
        String hashedpassword;
           hashedpassword = jploginpassword.getText();
           String userpassword = hashpassword(hashedpassword);
        
        try{
             con = DriverManager.getConnection(url,username,password);
            st = con.createStatement();
              String selecteevidence = "SELECT * FROM users WHERE  userusername = '"+txtusernamelogin.getText()+"' ";
            pst = con.prepareStatement(selecteevidence);
            rs = pst.executeQuery();
                  
            if(rs.next()){
               JOptionPane.showMessageDialog(null, "<HTML><i style=\"color: green; font-size: 12px;\">account found</i></HTML>","Student verdict",JOptionPane.WARNING_MESSAGE);
               String username = rs.getString("userusername");
               String password = rs.getString("userpassword");
               String privilage = rs.getString("userprivilege");
               if(userpassword == null ? password == null : userpassword.equals(password)){
                 JFrame dash = new Dashboard();
                dash.setVisible(true);
                Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
                int w = dim.width;
                int h = dim.height;
                dash.setSize(w, h);
                dash.setLocation(0,0);
                 dash.setExtendedState(JFrame.MAXIMIZED_BOTH);
                dash.setLayout(new GridBagLayout());
                this.dispose();  
               }else{
                  JOptionPane.showMessageDialog(null, "<HTML><i style=\"color: red; font-size: 12px;\">Wrong password</i></HTML>","Student verdict",JOptionPane.WARNING_MESSAGE); 
               }
           
            }else{
                JOptionPane.showMessageDialog(null, "<HTML><i style=\"color: red; font-size: 12px;\">Account ID not found</i></HTML>","Student verdict",JOptionPane.WARNING_MESSAGE);
            }
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex,"Student verdict",JOptionPane.WARNING_MESSAGE); 
        }
        
          /*/ */
    }//GEN-LAST:event_bntloginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntlogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jploginpassword;
    private javax.swing.JTextField txtusernamelogin;
    // End of variables declaration//GEN-END:variables
}
