/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentverdict;

import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.SQLIntegrityConstraintViolationException;
import java.sql.Statement;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author owner
 */
public class PassEvidence extends javax.swing.JPanel {

    /**
     * Creates new form PassEvidence
     */
    
  
    
             Statement st;
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    
    String username = "root";
    String password = "";
    String url = "jdbc:mysql://localhost:3306/student_verdict";
    
    int autoevidenceid = 1;
    
    public PassEvidence() {
        initComponents();
        loadnextid ();
        loadallstudent ();
        loadalviolation ();
    }
    
    //load next id number
    
       public void  loadnextid (){
         try{
             con = DriverManager.getConnection(url,username,password);
             st = con.createStatement();
             String selectevidenceid = "SELECT evidenceID FROM evidence  ";
            pst = con.prepareStatement(selectevidenceid);
            rs = pst.executeQuery();
                  
            while(rs.next()){
               
              autoevidenceid ++; 
             txtevidenceid.setText(autoevidenceid+"");
            
            }
            
           
         }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "error"+ ex,"Student verdict",JOptionPane.INFORMATION_MESSAGE);  
         }
    }
       
       //populate the regcombobox
       
        public void  loadallstudent (){
         try{
             con = DriverManager.getConnection(url,username,password);
             st = con.createStatement();
             String selectevidenceid = "SELECT studentREG FROM student  ";
            pst = con.prepareStatement(selectevidenceid);
            rs = pst.executeQuery();
                  
            while(rs.next()){
               
              cmbevidencestudentid.addItem(rs.getString("studentREG")); 
              cmbevidencestudentid.setEditable(true);
            
            }
            
           
         }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "error"+ ex,"Student verdict",JOptionPane.INFORMATION_MESSAGE);  
         }
    } 
        
        
         //populate the violation
       
        public void  loadalviolation (){
         try{
             con = DriverManager.getConnection(url,username,password);
             st = con.createStatement();
             String selecteviolation = "SELECT violationID FROM violation  ";
            pst = con.prepareStatement(selecteviolation);
            rs = pst.executeQuery();
                  
            while(rs.next()){
               
              cmbevidenceviolationid.addItem(rs.getString("violationID")); 
              cmbevidenceviolationid.setEditable(true);
            
            }
            
           
         }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "error"+ ex,"Student verdict",JOptionPane.INFORMATION_MESSAGE);  
         }
    }
        
    
    
     
    
       public void resizedimage(String resizedavatar) throws IOException{
        BufferedImage img = ImageIO.read(new File(resizedavatar));
Image scaled = img.getScaledInstance(200, 200, Image.SCALE_SMOOTH);
ImageIcon icon = new ImageIcon(scaled);
lbevidenceimage.setIcon(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpverdictevidence = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtevidencedescription = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jdevidenceDOA = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtevidenceid = new javax.swing.JTextField();
        txtevidencetype = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtevidencenote = new javax.swing.JTextArea();
        btnfilechooser = new javax.swing.JButton();
        lbevidenceimage = new javax.swing.JLabel();
        lbevidencelink = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        btnsavestaff = new javax.swing.JButton();
        cmbevidencestudentid = new javax.swing.JComboBox<>();
        cmbevidenceviolationid = new javax.swing.JComboBox<>();
        lbbtnclose = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jpverdictevidence.setBackground(new java.awt.Color(255, 255, 255));
        jpverdictevidence.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtevidencedescription.setColumns(20);
        txtevidencedescription.setRows(5);
        jScrollPane1.setViewportView(txtevidencedescription);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Evidence Description :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Date Of Add :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Student REG :");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Violation ID :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Evidence ID :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Evidence Type:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Evidence Note :");

        txtevidencenote.setColumns(20);
        txtevidencenote.setRows(5);
        jScrollPane2.setViewportView(txtevidencenote);

        btnfilechooser.setText("Choose file");
        btnfilechooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfilechooserActionPerformed(evt);
            }
        });

        lbevidenceimage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Media Link :");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setText("Reset Form");

        btnsavestaff.setBackground(new java.awt.Color(0, 204, 102));
        btnsavestaff.setText("Submit Evidence");
        btnsavestaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsavestaffActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(btnsavestaff, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 189, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(btnsavestaff, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 11, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        cmbevidenceviolationid.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Violation" }));

        javax.swing.GroupLayout jpverdictevidenceLayout = new javax.swing.GroupLayout(jpverdictevidence);
        jpverdictevidence.setLayout(jpverdictevidenceLayout);
        jpverdictevidenceLayout.setHorizontalGroup(
            jpverdictevidenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpverdictevidenceLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jpverdictevidenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpverdictevidenceLayout.createSequentialGroup()
                        .addGroup(jpverdictevidenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpverdictevidenceLayout.createSequentialGroup()
                                .addGap(199, 199, 199)
                                .addGroup(jpverdictevidenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtevidencetype, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtevidenceid, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jpverdictevidenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpverdictevidenceLayout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpverdictevidenceLayout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(133, 133, 133))))
                    .addGroup(jpverdictevidenceLayout.createSequentialGroup()
                        .addGroup(jpverdictevidenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpverdictevidenceLayout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(jpverdictevidenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpverdictevidenceLayout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(70, 70, 70))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jpverdictevidenceLayout.createSequentialGroup()
                                .addGroup(jpverdictevidenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(39, 39, 39)
                                .addGroup(jpverdictevidenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbevidencestudentid, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jdevidenceDOA, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jpverdictevidenceLayout.createSequentialGroup()
                                        .addComponent(cmbevidenceviolationid, 0, 220, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))))
                        .addGroup(jpverdictevidenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpverdictevidenceLayout.createSequentialGroup()
                                .addComponent(lbevidencelink, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpverdictevidenceLayout.createSequentialGroup()
                                .addComponent(lbevidenceimage, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(81, 81, 81))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpverdictevidenceLayout.createSequentialGroup()
                                .addComponent(btnfilechooser, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(106, 106, 106))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpverdictevidenceLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109))
            .addGroup(jpverdictevidenceLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jpverdictevidenceLayout.setVerticalGroup(
            jpverdictevidenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpverdictevidenceLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel6)
                .addGap(16, 16, 16)
                .addGroup(jpverdictevidenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpverdictevidenceLayout.createSequentialGroup()
                        .addGroup(jpverdictevidenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtevidenceid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(29, 29, 29)
                        .addGroup(jpverdictevidenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtevidencetype, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(jpverdictevidenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpverdictevidenceLayout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jLabel1))
                            .addGroup(jpverdictevidenceLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(cmbevidenceviolationid, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jpverdictevidenceLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(lbevidencelink, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jpverdictevidenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpverdictevidenceLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jpverdictevidenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(cmbevidencestudentid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jpverdictevidenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jdevidenceDOA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpverdictevidenceLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lbevidenceimage, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnfilechooser)))
                .addGap(32, 32, 32)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        lbbtnclose.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbbtnclose.setForeground(new java.awt.Color(204, 0, 0));
        lbbtnclose.setText("X");
        lbbtnclose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbbtnclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbbtncloseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jpverdictevidence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addComponent(lbbtnclose)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbbtnclose, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpverdictevidence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnfilechooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfilechooserActionPerformed
        JFrame frame = new JFrame("Swing Tester");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        frame.setSize(560, 200);
        frame.setLocationRelativeTo(null);
        frame.setVisible(false);

        JFileChooser fileChooser = new JFileChooser("C:\\Projects\\StudentVerdict\\images");
        int option = fileChooser.showOpenDialog(frame);
        if(option == JFileChooser.APPROVE_OPTION){
            File file = fileChooser.getSelectedFile();
            File folder = fileChooser.getCurrentDirectory();
            lbevidencelink.setText(folder.getAbsolutePath() + "/" + file.getName());
            String resizedavatar = folder.getAbsolutePath() + "/" + file.getName();

            // try load resized image

            try {
                // TODO add your handling code here:
                resizedimage(resizedavatar);
            } catch (IOException ex) {
                JOptionPane.showConfirmDialog(null, ex );
            }
        }else{
            lbevidencelink.setText("Open command canceled");
            //loadavater();
        }
    }//GEN-LAST:event_btnfilechooserActionPerformed

    private void btnsavestaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsavestaffActionPerformed
        // TODO add your handling code here:

        try {

            // get gender
         

            // GET Date

            java.util.Date dob;
            java.sql.Date evidencedoa;
            dob =  jdevidenceDOA.getDate();
            evidencedoa = new java.sql.Date(dob.getTime());
            // TODO add your handling code here:
            con = DriverManager.getConnection(url,username,password);
            st = con.createStatement();
            // inserting student personal details
            String sqlevidencedetails = "INSERT INTO evidence (evidenceID,evidencetype,evidencedescription,evidencemedia,evidencedocument,"
            + "violationID,studentREG,evidenceDOA) VALUES"
            + " ('"+txtevidenceid.getText()+"','"+txtevidencetype.getText()+"','"+txtevidencedescription.getText()+"','"+lbevidencelink.getText()+"',"
            + "'"+txtevidencenote.getText()+"','"+cmbevidenceviolationid.getSelectedItem()+"','"+cmbevidencestudentid.getSelectedItem()+"','"+evidencedoa+"')";
            st.execute(sqlevidencedetails);
            JOptionPane.showMessageDialog(null, "<HTML><i style=\"color: green; font-size: 12px;\">New Evidence Registered</i></HTML>","Student verdict",JOptionPane.INFORMATION_MESSAGE);
        
     
        }catch(SQLIntegrityConstraintViolationException e){
            JOptionPane.showMessageDialog(null, "<HTML><i style=\"color: red; font-size: 12px;\">Evidence Already Exists</i></HTML>","Student verdict",JOptionPane.WARNING_MESSAGE);
        }
        catch(HeadlessException | SQLException ex){
            JOptionPane.showMessageDialog(null, "error"+ ex,"Student verdict",JOptionPane.INFORMATION_MESSAGE);

        }
        catch(NullPointerException npx){
            
            JOptionPane.showMessageDialog(null,"Please select Date !","Student verdict",JOptionPane.INFORMATION_MESSAGE);
          
        }
    }//GEN-LAST:event_btnsavestaffActionPerformed

    private void lbbtncloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbbtncloseMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_lbbtncloseMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnfilechooser;
    private javax.swing.JButton btnsavestaff;
    private javax.swing.JComboBox<String> cmbevidencestudentid;
    private javax.swing.JComboBox<String> cmbevidenceviolationid;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private com.toedter.calendar.JDateChooser jdevidenceDOA;
    private javax.swing.JPanel jpverdictevidence;
    private javax.swing.JLabel lbbtnclose;
    private javax.swing.JLabel lbevidenceimage;
    private javax.swing.JTextField lbevidencelink;
    private javax.swing.JTextArea txtevidencedescription;
    private javax.swing.JTextField txtevidenceid;
    private javax.swing.JTextArea txtevidencenote;
    private javax.swing.JTextField txtevidencetype;
    // End of variables declaration//GEN-END:variables
}
